### ISSUE TITLE
Child always rebuilding on switch

### ISSUE THREAD

**Issue by pblinux** [Salby/morph#10]
Hi.
Is there any way to persist the child's state? Every time I make the child switch, it is rebuilt again.

I'm working with Statefull widgets and switching in a bottomNavigationBar. I even tried with the AutomaticKeepAliveClientMixin.

Thanks (btw, I really like transitions, great work).

**Comment by git-gz** [comment]
> Hi.
> Is there any way to persist the child's state? Every time I make the child switch, it is rebuilt again.
> 
> I'm working with Statefull widgets and switching in a bottomNavigationBar. I even tried with the AutomaticKeepAliveClientMixin.
> 
> Thanks (btw, I really like transitions, great work).
**This will solve your problem**
`MorpheusTabView(`
                   `   curve: Curves.easeInOutSine,`
                   `   duration: Duration(milliseconds: 600),`
                   `   child: IndexedStack(`
                     `     index: currentIndex,`
                      `    children: <Widget>[`
                       `       Container(color: Colors.red),`
                        `      Container(color: Colors.yellow),`
                       `       Container(color: Colors.blue),`
                     `     ],`
                   `    ),`
                 ` )`

**Comment by pblinux** [comment]
Awesome @git-gz thank you!

**Comment by Salby** [comment]
Sorry I didn't have the time to answer your question, thank you @git-gz for figuring it out :+1:

I'm closing this issue now, might add this example in the documentation if others are looking for some similar functionality.
