### ISSUE TITLE
Maintaining state

### ISSUE THREAD

**Issue by aleksandar-radivojevic** [Salby/morph#17]
Is there a way to maintain state on MorpheusPageRoute, because I need this functionality for IOS, user can't navigate back with a back swipe..

**Comment by Salby** [comment]
Thank you for submitting your issue.

Are you implementing the swipe-back gesture yourself? There currently aren't any plans to implement route gestures but that may change in the future.

**Comment by aleksandar-radivojevic** [comment]
I don't know how to implement gestures. It would be great if you change your plans. :D

**Comment by Salby** [comment]
Closing this for now. I'll let you know if I change my plans :)
