### ISSUE TITLE
Expand from circular widget like FAB

### ISSUE THREAD

**Issue by freesailor** [Salby/morph#20]
Hi how to use MorpheusPageRoute to create a radial expansion from a floating action button to the new screen?
This feature is implemented in the package **animations**, but I prefer using your plugin.
Thanks

**Comment by Salby** [comment]
Thank you for taking the time to ask a question.

You can use the `borderRadius` parameter when creating a `MorpheusPageRoute` to set the initial shape of the transition.

If you're working with a standard FAB you can set the border radius to at least 28 :)

I hope this solved your issue.

**Comment by Salby** [comment]
Closing this issue.

Feel free to open another issue if you have any more problems.
